controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CForm;
use app\models\Dirs;
use app\models\Files;
use app\models\UploadForm;
use Faker\Provider\File;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    const FILE_PATH_REGEXP = '/(.*)\/(.*)\.(.*)/';

    const FILE_NOT_FOUND_MESSAGE = 'Файл не найдет!';

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionFiles() {
        return $this->render('files',['data'=>Files::getUploadCatalog()]);
    }

    public function actionUpload() {

        $model = new UploadForm();

        if (Yii::$app->request->isPost) {

            $model -> load(Yii::$app->request->post());

            $model -> textFiles = UploadedFile::getInstances($model, 'textFiles');

            if ($model -> upload()) {

                return Yii::$app->getResponse() -> redirect(['site/files']);

            }
        }

        $dirs = ArrayHelper::map(Dirs::getIncomplateDirs(),'id','name');

        $dirs['new']= 'Новая папка';

        return $this->render('upload', ['model' => $model,'dirs'=>$dirs]);
    }

    public function actionShowfile() {

        $request = Yii::$app -> getRequest();

        if ($request->isAjax) {


            $file = Files::findOne($request -> get('f'));

            if ($file instanceof Files && is_file($file->path)) {

                return file_get_contents($file->path);

            } else {

                return self::FILE_NOT_FOUND_MESSAGE;
            }


        } else {

            return Yii::$app -> getResponse() -> redirect('index.php');

        }
    }

    public function actionDeletefile() {

        $request = Yii::$app->getRequest();

        if ($request->isAjax) {

            $file = Files::findOne($request -> get('f'));

            if ($file instanceof Files && is_file($file->path)) {

                unlink($file->path);

                $file->delete();

                $answer = $this->renderAjax('files_list', ['data'=>Files::getUploadCatalog()]);

            } else {

                $answer = self::FILE_NOT_FOUND_MESSAGE;
            }

            return $answer;

        } else {

            return Yii::$app -> getResponse() -> redirect('index.php');

        }
    }

    public function actionDownload() {

        $request = Yii::$app->request;

        $file = Files::findOne($request -> get('f'));

        if ($file instanceof Files && is_file($file->path)) {

            $answer = Yii::$app->response->sendFile($file->path);

        } else {

            $answer = self::FILE_NOT_FOUND_MESSAGE;
        }

        return $answer;
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/files.php
<?php
$this ->registerJsFile('js/list.js');
?>

<h1>Список файлов</h1>
<div class="dir-wrap">
<?php
include_once "files_list.php";
?>
</div>

<div class="overlay" title="окно"></div>
<div class="popup">
    <div class="close_window">x</div>
    <pre></pre>
</div>

<div class="action-popup">
    <a href="" action="show">Просмотреть</a>
    <a href="" action="delete">Удалить</a>
    <a href="" action="download">Скачать</a>
</div>

views/site/files_list.php
<?php
use yii\helpers\Html;
if (empty($data)) {

echo "<h3>Загруженых файлов нет</h3>";

} else {

foreach ($data as $dir => $files) {

$dir_href = Html::a('/' . $dir, null, ['class' => 'dir-href','name'=>$dir]) . "<br>";

$files_hrefs = [];

foreach ($files as $file) {
$filename="$dir/" . $file['basename']. '.' . $file['extension'];
$files_hrefs[] = Html::a($file['basename'] . "." . $file['extension'], null, ['class' => 'file-href','id'=>$file['id']]);
}

$files_container = Html::tag('div', implode('<br>',$files_hrefs),['class'=>'files-container','id'=>$dir]);
echo  $dir_href . $files_container;
}
}

views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Загрузчик файлов';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Добро пожаловать</h1>

        <p class="lead">Выберете что сделать</p>
        <p><?php echo Html::a('Загрузить файлы',array('site/upload'),array('class'=>"btn btn-lg btn-success"))?></p>
        <p><?php echo Html::a('Просмотреть файлы',array('site/files'),array('class'=>"btn btn-lg btn-success"))?></p>
    </div>

    <div class="body-content">



    </div>
</div>

views/site/upload.php
<?php
use yii\widgets\ActiveForm;
$this ->registerJsFile('js/upload.js');

?>

<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

<?= $form->field($model, 'uploaddir')->dropDownList($dirs) ?>
<?= $form->field($model, 'newdir',['options'=>['class'=>'hidden']])->input('text')?>
<?= $form->field($model, 'textFiles[]')->fileInput(['multiple' => true]) ?>

    <button>Submit</button>

<?php ActiveForm::end() ?>